import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/ApexLogo.jpg" type="image/jpeg" />
        <title>Apex Webs | Professional Web Solutions in Kenya</title>
        <meta name="description" content="Kenyan web solutions for SMEs, schools, and startups. Custom websites, hosting, and API integrations." />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ display: 'flex', alignItems: 'center', padding: '1rem', borderBottom: '1px solid #eee' }}>
          <Image src="/images/ApexLogo.jpg" alt="Apex Webs Logo" width={48} height={48} style={{ borderRadius: '8px', marginRight: '1rem' }} />
          <div>
            <h1 style={{ margin: 0, fontSize: '1.5rem', fontWeight: 700 }}>Apex Webs</h1>
            <span style={{ fontSize: '1rem', color: '#00704A' }}><em>Pamoja Tunaweza</em> - Together We Can</span>
          </div>
        </header>
        <main>{children}</main>
        <footer style={{ textAlign: 'center', padding: '1rem', borderTop: '1px solid #eee', marginTop: '2rem', color: '#888' }}>
          &copy; {new Date().getFullYear()} Apex Webs. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
