import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
// import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/ApexLogo.jpg" type="image/jpeg" />
        <title>Apex Webs | Professional Web Solutions in Kenya</title>
        <meta name="description" content="Kenyan web solutions for SMEs, schools, and startups. Custom websites, hosting, and API integrations." />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ margin: 0, padding: 0 }}>
        {/* Fixed Navbar with Logo and Title */}
        <div style={{ position: 'fixed', top: 18, left: 0, width: '100%', background: 'rgba(0,0,0,0.4)', zIndex: 100, boxShadow: '0 2px 12px #0006', borderBottom: '1.5px solid #222', borderTopLeftRadius: 10, borderTopRightRadius: 10, transition: 'background 0.2s' }}>
          <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0.7rem 2rem 0.7rem 1rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <Image src="/images/ApexLogo.jpg" alt="Apex Webs Logo" width={38} height={38} style={{ borderRadius: '8px', background: 'transparent' }} />
              <span style={{ fontWeight: 800, fontSize: '1.6rem', color: '#fff', letterSpacing: '-1px', fontFamily: 'inherit' }}>Apex Webs</span>
            </div>
            <nav className="apex-navbar-links" style={{ display: 'flex', alignItems: 'center', gap: '2.2rem' }}>
              <a href="#hero">Home</a>
              <a href="#services">Services</a>
              <a href="#projects">Projects</a>
              <a href="#about">About</a>
              <a href="#contact">Contact</a>
            </nav>
          </div>
        </div>
        {/* Spacer for fixed navbar - removed to eliminate black gap above hero */}
        <main style={{ minHeight: '70vh', background: 'linear-gradient(120deg, #f8fafc 60%, #e0f7fa 100%)', paddingBottom: '2rem' }}>{children}</main>

        {/* Navbar Link Styles */}
        <style>{`
          .apex-navbar-links a {
            color: #fff !important;
            font-weight: 700;
            text-decoration: none;
            font-size: 1.08rem;
            transition: color 0.3s, border-bottom 0.3s, background 0.3s;
            border-bottom: 2.5px solid transparent;
            border-radius: 2px;
            padding-bottom: 2px;
            cursor: pointer;
          }
          .apex-navbar-links a:hover {
            color: #0ea5e9 !important;
            border-bottom: 2.5px solid #0ea5e9;
            background: rgba(14,165,233,0.07);
          }
          .apex-navbar-links a.active {
            color: #0ea5e9 !important;
            border-bottom: 2.5px solid #0ea5e9;
            background: rgba(14,165,233,0.07);
          }
          .hero-btn {
            border: 2px solid transparent;
            transition: border 0.2s, color 0.2s, background 0.2s;
          }
          .hero-btn:hover {
            border: 2px solid #e53935 !important;
            color: #e53935 !important;
            background: #fff !important;
            box-shadow: 0 2px 16px #e5393555;
          }
        `}</style>
        <footer style={{ textAlign: 'center', padding: '1rem', borderTop: '1px solid #eee', marginTop: '2rem', color: '#888' }}>
          &copy; {new Date().getFullYear()} Apex Webs. All rights reserved.
        </footer>

        {/* NavLink component for active/teal logic */}
        <script type="text/javascript" dangerouslySetInnerHTML={{ __html: `
          (function() {
            function setActiveLink() {
              var links = document.querySelectorAll('.apex-navbar-links a');
              var fromTop = window.scrollY + 100;
              var sections = ['hero','services','projects','about','contact'].map(id => document.getElementById(id));
              let found = false;
              for (let i = 0; i < sections.length; i++) {
                if (sections[i] && fromTop >= sections[i].offsetTop) {
                  links.forEach(l => l.classList.remove('active'));
                  links[i].classList.add('active');
                  found = true;
                }
              }
              if (!found) links.forEach(l => l.classList.remove('active'));
            }
            window.addEventListener('scroll', setActiveLink);
            setActiveLink();
            document.querySelectorAll('.apex-navbar-links a').forEach(link => {
              link.addEventListener('click', function(e) {
                const href = this.getAttribute('href');
                if (href && href.startsWith('#')) {
                  e.preventDefault();
                  document.querySelector(href).scrollIntoView({ behavior: 'smooth' });
                }
              });
            });
          })();
        `}} />
      </body>
    </html>
  );
}
